[tool.ruff]
line-length = 79
extend-exclude = ['venv', 'migrations', 'app/settings.py', 'manage.py']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.taskipy.tasks]
lint = 'ruff check'
# pre_format = 'ruff check --fix'
format = 'ruff format'
run = 'py manage.py runserver'
freeze = 'pip freeze > requirements.txt'
