# Generated by Django 5.2.1 on 2025-05-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='genre',
            field=models.CharField(choices=[('Male', 'Masculino'), ('Female', 'Feminino')], default='Male'),
        ),
    ]
